version: "3.8"
services:
  dreamtourismit:
    build: .
    image: demodreamtourismit-dreamtourismit
    container_name: tourismitapp
    restart: always
    ports:
      - 3010:3000
    # env_file:
    #   - .env.local
    networks:
      - tourismitnet
    volumes:
      - tourismitapp_data:/usr/share/tourismitapp/data

networks:
  tourismitnet:
    driver: bridge
volumes:
  tourismitapp_data:
