version: "3.8"
services:
  dreamtourismitlive:
    build: .
    image: dreamtourismit-dreamtourismitlive
    container_name: dremtourismitapp
    restart: always
    ports:
      - 3013:3000
    # env_file:
    #   - .env.local
    networks:
      - dreamtourismitnet
    volumes:
      - dremtourismitapp_data:/usr/share/dremtourismitapp/data

networks:
  dreamtourismitnet:
    driver: bridge
volumes:
  dremtourismitapp_data:
